# Generated by Django 4.2.13 on 2024-05-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradTools_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
