# Generated by Django 4.2.13 on 2024-05-19 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradTools_app', '0002_course_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='top',
        ),
    ]
