# Generated by Django 4.2.13 on 2024-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradTools_app', '0005_alter_course_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
