# Generated by Django 4.2.13 on 2024-05-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradTools_app', '0006_alter_course_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
