# Generated by Django 4.2.13 on 2024-05-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradTools_app', '0007_newsitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
